### ISSUE TITLE
[EPIC] Metadata Library with github-backed MetaStore

### ISSUE THREAD

**Issue by risenW** [datopian/metastore-lib-js#1]
# Dataset Metadata Library and API for github-backed MetaStore

The dataset metadata library/API handles saving a new or existing dataset metadata to the backend (in this case github).

Context: overall flow is described in https://github.com/datopian/gift-portal/issues/23

Relevant part here is last step:

* Save dataset info (data package)
  * Use POST /api/dataset (or whatever url we have)
  * Or use our own library to do post directly to github ... in the app ... (assuming no CORs issues, correct credentials via oauth etc)

## Acceptance

Unlike metastore-lib we could assume the repo exists so we don't need to handle that (that will be done by admin separately)

* [x] Document API of existing metastore-lib https://github.com/datopian/metastore-lib in a simple way and identify key methods we need **DONE. See https://hackmd.io/RcL-HIv1R76VtQwdFd8VfA. Key methods are `StorageBackend create,update,fetch,delete`. We need to implement `create, update`. May want to implement `fetch` for testing purposes plus because could be useful in other parts e.g. creating MetaStore in the first place. I have added new acceptance items for them here in this section**
* [x] Implement these key methods in both FileSystem and Github storage backends **Done** See #9 and #8 
  * [x] `create(objectId, metadata, author=None, message=None)`
    * [x] FileSystem
    * [x] GitHub
  * [x] `update(objectId, metadata, author=None, message=None)` (FUTURE: support partial and base_revision_ref)
    * [x] FileSystem
    * [x] GitHub
  * [x] `fetch(objectId, revisionRef=None)`
    * [x] FileSystem
    * [x] GitHub

## Tasks

* [x] Research python metastore-lib (1-2h) **DONE: https://hackmd.io/RcL-HIv1R76VtQwdFd8VfA**
* [x] Document methods and classes needed **DONE See analysis below**
* [x] Setup github repo (metastore-lib-js) for Javascript based Dataset api **Done*** https://github.com/datopian/metastore-lib-js
* [x] Abstract Storage class
* [x] Filesystem backend
  * [x] `create`
    * [x] Write a test
    * [x] Get the test passing
  * [x] `update`
  * [x] `fetch`
* [x] GitHub backend
    * [x] `create`
  * [x] `update`
  * [x] `fetch`
  * [x] decide on github library to use **DONE. We decide to use [rest.js](https://github.com/octokit/rest.js/) over [Github.js](https://github.com/github-tools/github) as it is popular (4.4k stars), well maintained and has a developer friendly API.**
    * Using Graph API instead of Rest? **ANS: No The github graphql api does not yet support commits to repositories, so we can't use this for now.**
  * [x] `create`
    * Unlike python we want to handle case where repo exists already (but datapackage.json does not ...)

## Metastore Lib Documentation

The dataset metadata library/API handles saving a new or existing dataset metadata to the backend (in this case github).

## Detailed Analysis and Notes

```javascript=
import metastore from 'metastore-lib-js'

const config = {
    token: "dgkjdgjkd",
    org: "gift-data",
    metadataPath: "datapackage.json"
    author: "John Doe"
}

let store = new metastore.GithubBackend(config)
```

### Create metadata

Using the metastore instance above, we can store new metadata for an object by calling the metastore create method:

```javascript=
let objectId = "France-2020-budget" //This is also the repo name
# store a Frictionless Data Package https://specs.rictionless.io/data-package/
let metadata = {"name": "mypackage",
                    "version": "1.0.0",
                    "resources": [
                       # ...
                     ]}
let objectInfo = store.create(objectId, metadata)
```

The returned objectInfo will be an object with some information about the stored package revision.

### Update metadata

To update an existing package, provide the package_id and the metadata as shown below:
```javascript=
let package_id = "France-2020-budget" //This is also the repo name
let datapackage = {"name": "mypackage",
                    "version": "1.1.0",
                    "resources": [
                       # ...
                     ]}
let package_info = metastoreBackend.update(package_id, datapackage)
```

### Fetch metadata

You can retreive an existing data package using the fetch method on the GithubBackend class as shown below:
```javascript=
let package_id = "France-2020-budget" //This is also the repo name
let datapackage = metastoreBackend.fetch(package_id)
```

### Datatypes, Classes and Methods

Data types, classes and methods for packages & related models.

#### Object Info

The PackageInfo class holds metadata about a created package including version and revision number, created date, and basic description. 
```javascript=
/**
    author: Optional[str] = None
    created: datetime = None
    description: Optional[str] = None
    package: Optional[DataPackageType] = None
    package_id: str = None
    revision: str = None
**/
class metastore.PackageInfo{
    constructor(package_id,revision,created,author,description,package){
        this.package_id = package_id
        this.revision = revision || 1.0.0
        this.created = new Date()
        this.author = {name: "John Doe", email: "johndoe@mail.com"
        this.description = description || ""
        this.package = package || {}
    }
}
    
```    

### Storage Backend Interface

The storage bankend class shows CRUD methods for handling data packages with Github API. Internally we use [rest.js](https://octokit.github.io/rest.js/v18) library to handle interactions with Github API.

* Create a repository in an organisation ==> https://octokit.github.io/rest.js/v18#repos-create-in-org
* Upload/create and update file in a repository ==> https://octokit.github.io/rest.js/v18#repos-create-or-update-file-contents

```javascript=

class metastore.GithubBackend {
    constructor(config){
        this.personal_access_token = config.personal_access_token
        this.org_name = config.org_name
        this.author = config.author         
    }
    
    /**
     * Uploads a new data package
     * 
     * returns
     * PackageInfo
     **/
    upload(package_id, metadata, author, message){
        // creates metadata and uploads to Github with github client
    }
    
    /**
     * Deletes a data package from Github
     * 
     * Throws: Not found if the package does not exist
     * 
     * Returns None
    **/
    remove(package_id){
        //delete ops
    }
    
    /**
     * Update or partial update (patch) a data package
     * 
     * Returns PackageInfo
     **/
    update(package_id, metadata, author, message){
        //perform update
    }
    
    /**
     * Gets a data package by ID
     * 
     * Returns datapackage Object
     **/
    fetch(package_id){
        //perform update
    }
    
}
```

**Comment by risenW** [comment]
**FIXED** see #8 , #9 and #10
