### ISSUE TITLE
Generate LFS pointer files before metadata is uploaded to Github Backend

### ISSUE THREAD

**Issue by risenW** [datopian/metastore-lib-js#11]
LFS files (.gitattributes, .lfsconfig, and pointer files) are generated from metadata resource, before uploading to Github backend. 

### Acceptance
* [x]  I have LFS config files generated from a metadata before upload to github backend **Done** See https://github.com/datopian/metastore-lib-js/pull/12/commits/d3e2d20d749ce18b17f8dc19beda37042b5115d0
   * [x]  .gitattributes
   * [x]  .lfsconfig
   * [x] pointer files for each resource saved in data folder
* [x] On upload to github backend, I have the following files as part of the repository **Done** See images below
    * [x]  .gitattributes
   * [x]  .lfsconfig
   * [x] data with corresponding pointer files
 * [x] Documentation is updated to show changes **Done** See https://github.com/datopian/metastore-lib-js/blob/main/README.md

<img width="1333" alt="Screen Shot 2021-01-14 at 1 39 55 PM" src="https://user-images.githubusercontent.com/29900845/104593524-1e52c980-5670-11eb-9d5e-95d2285fa10b.png">
<img width="889" alt="Screen Shot 2021-01-14 at 1 40 12 PM" src="https://user-images.githubusercontent.com/29900845/104593541-21e65080-5670-11eb-9c89-60d8be39a614.png">
<img width="774" alt="Screen Shot 2021-01-14 at 1 40 24 PM" src="https://user-images.githubusercontent.com/29900845/104593543-227ee700-5670-11eb-926e-5c574cefd318.png">
<img width="1044" alt="Screen Shot 2021-01-14 at 1 40 36 PM" src="https://user-images.githubusercontent.com/29900845/104593544-23177d80-5670-11eb-9d36-880b1332f302.png">
<img width="906" alt="Screen Shot 2021-01-14 at 1 40 49 PM" src="https://user-images.githubusercontent.com/29900845/104593546-23b01400-5670-11eb-9ba0-b38a1e273cb2.png">

### Task
* [x] Port LFS helper files from https://github.com/datopian/metastore-lib/blob/master/metastore/backend/git_lfs_helpers.py
* [x] Port LFS config file generation functions from https://github.com/datopian/metastore-lib/blob/master/metastore/backend/github/storage.py 
* [x] Update create method in github backend to use LFS create function
* [x] Update create method in github backend to upload multiple files at once. 
* [x] Update docstring of methods and documentation in ReadMe
