### ISSUE TITLE
Set up Javascript library locally with linting support and compilation

### ISSUE THREAD

**Issue by risenW** [datopian/metastore-lib-js#2]
Set up a new Javascript library for easy publication to npm. The library should have linting enabled, webpack compilation, and some basic tests. Also, we need to set up GitHub actions. 

## Acceptance
* [x] I have a Javascript package with babel compilation enabled __Done__
* [x] I can run `npm test` to execute unit tests __Done__
* [x] I can publish a package to npm by running `npm publish` __Done__
* [x]  I have GitHub actions enabled and will run on every push to the repo __Done__
<img width="1106" alt="Screen Shot 2021-01-05 at 2 07 37 PM" src="https://user-images.githubusercontent.com/29900845/103649886-7b0eff80-4f5f-11eb-9562-a3fc91525a1f.png">

![Screen Shot 2021-01-05 at 2 08 00 PM](https://user-images.githubusercontent.com/29900845/103650044-ba3d5080-4f5f-11eb-80b7-d808a9841553.png)

## Task
* [x] Set up linting
* [x] Configure  babel
* [x] Add unit tests using mocha and chai
* [x] Add github actions to CI
