### ISSUE TITLE
Implement Filesystem backend with Create, Fetch and Update methods

### ISSUE THREAD

**Issue by risenW** [datopian/metastore-lib-js#3]
As described in the epic #1 , implement all methods needed to successfully create, update and fetch metadata from File System backend. See the analysis below.

### Acceptance

* [x] Implement these key methods in both FileSystem
  * [x] `create(objectId, metadata, author=None, message=None)` **Done** 
  
![Screen Shot 2021-01-06 at 3 36 52 PM](https://user-images.githubusercontent.com/29900845/103780544-6309af80-5035-11eb-97bd-358ec5c58bac.png)

  * [x] `update(objectId, metadata, author=None, message=None)` (FUTURE: support partial and base_revision_ref)
  
![Screen Shot 2021-01-06 at 3 37 48 PM](https://user-images.githubusercontent.com/29900845/103780671-94827b00-5035-11eb-962e-5542abe7fad5.png)

  * [x] `fetch(objectId, revisionRef=None)`
 
![Screen Shot 2021-01-06 at 3 38 54 PM](https://user-images.githubusercontent.com/29900845/103780697-9f3d1000-5035-11eb-937c-1553e5d2bd88.png)

## Tasks
* [x] Abstract Storage class
* [x] Filesystem backend
  * [x] `create`
    * [x] Write a test
    * [x] Get the test passing
  * [x] `update`
     * [x] Write a test
     * [x] Get the test passing
  * [x] `fetch`
    * [x] Write a test
    * [x] Get the test passing

## Detailed Analysis and Notes

```javascript=
import metastore from 'metastore-lib-js'

const config = {
    token: "dgkjdgjkd",
    org: "gift-data",
    metadataPath: "datapackage.json"
    author: "John Doe"
}

let store = new metastore.FileSystemBackend(config)
```

### Create metadata

Using the metastore instance above, we can store new metadata for an object by calling the metastore create method:

```javascript=
let objectId = "France-2020-budget" //This is also the repo name
# store a Frictionless Data Package https://specs.rictionless.io/data-package/
let metadata = {"name": "mypackage",
                    "version": "1.0.0",
                    "resources": [
                       # ...
                     ]}
let objectInfo = store.create(objectId, metadata)
```

The returned objectInfo will be an object with some information about the stored package revision.

### Update metadata

To update an existing package, provide the package_id and the metadata as shown below:
```javascript=
let package_id = "France-2020-budget" //This is also the repo name
let datapackage = {"name": "mypackage",
                    "version": "1.1.0",
                    "resources": [
                       # ...
                     ]}
let package_info = metastoreBackend.update(package_id, datapackage)
```

### Fetch metadata

You can retreive an existing data package using the fetch method on the GithubBackend class as shown below:
```javascript=
let package_id = "France-2020-budget" //This is also the repo name
let datapackage = metastoreBackend.fetch(package_id)
```

### Datatypes, Classes and Methods

Data types, classes and methods for packages & related models.

#### Object Info

The PackageInfo class holds metadata about a created package including version and revision number, created date, and basic description. 
```javascript=
/**
    author: Optional[str] = None
    created: datetime = None
    description: Optional[str] = None
    package: Optional[DataPackageType] = None
    package_id: str = None
    revision: str = None
**/
class metastore.PackageInfo{
    constructor(package_id,revision,created,author,description,package){
        this.package_id = package_id
        this.revision = revision || 1.0.0
        this.created = new Date()
        this.author = {name: "John Doe", email: "johndoe@mail.com"
        this.description = description || ""
        this.package = package || {}
    }
}
    
```    

### Storage Backend Interface

The storage bankend class shows CRUD methods for handling data packages with Github API. Internally we use [rest.js](https://octokit.github.io/rest.js/v18) library to handle interactions with Github API.

* Create a repository in an organisation ==> https://octokit.github.io/rest.js/v18#repos-create-in-org
* Upload/create and update file in a repository ==> https://octokit.github.io/rest.js/v18#repos-create-or-update-file-contents

```javascript=

class metastore.GithubBackend {
    constructor(config){
        this.personal_access_token = config.personal_access_token
        this.org_name = config.org_name
        this.author = config.author         
    }
    
    /**
     * Uploads a new data package
     * 
     * returns
     * PackageInfo
     **/
    upload(package_id, metadata, author, message){
        // creates metadata and uploads to Github with github client
    }
    
    /**
     * Deletes a data package from Github
     * 
     * Throws: Not found if the package does not exist
     * 
     * Returns None
    **/
    remove(package_id){
        //delete ops
    }
    
    /**
     * Update or partial update (patch) a data package
     * 
     * Returns PackageInfo
     **/
    update(package_id, metadata, author, message){
        //perform update
    }
    
    /**
     * Gets a data package by ID
     * 
     * Returns datapackage Object
     **/
    fetch(package_id){
        //perform update
    }
    
}
```
