### ISSUE TITLE
Setup Github CI Actions

### ISSUE THREAD

**Issue by risenW** [datopian/metastore-lib-js#6]
## Acceptance
* [ ] I have GitHub actions running on every commit to the repo

## Task
* [ ] Set up Github actions
* [ ] Add commands to run test and build on every commit
