### ISSUE TITLE
Implement Github backend with Create, Fetch and Update methods

### ISSUE THREAD

**Issue by risenW** [datopian/metastore-lib-js#7]
As described in the epic #1 , implement all methods needed to successfully create, update and fetch metadata from Github  backend. See the analysis below.

### Acceptance

* [x] Implement these key methods in Github backend **Done** See images below
  * [x] `create(objectId, metadata, author=None, message=None)` **Done** See images below
  * [x] `update(objectId, metadata, author=None, message=None)` (FUTURE: support partial and base_revision_ref) **Done** See images below
  * [x] `fetch(objectId, revisionRef=None)` **Done** See images below

#### Create
<img width="836" alt="Screen Shot 2021-01-11 at 10 35 21 AM" src="https://user-images.githubusercontent.com/29900845/104165133-41277880-53f9-11eb-963a-1a833768b552.png">

<img width="1290" alt="Screen Shot 2021-01-11 at 10 35 44 AM" src="https://user-images.githubusercontent.com/29900845/104165240-6320fb00-53f9-11eb-8f28-150ba6603e61.png">

#### Update
<img width="852" alt="Screen Shot 2021-01-11 at 10 37 12 AM" src="https://user-images.githubusercontent.com/29900845/104165276-6f0cbd00-53f9-11eb-8288-a1605df6e30d.png">

<img width="1021" alt="Screen Shot 2021-01-11 at 10 37 26 AM" src="https://user-images.githubusercontent.com/29900845/104165301-77fd8e80-53f9-11eb-9fe2-8c264dceb0f1.png">

#### Fetch
<img width="853" alt="Screen Shot 2021-01-11 at 10 33 02 AM" src="https://user-images.githubusercontent.com/29900845/104165338-8350ba00-53f9-11eb-9092-bdad8862426c.png">

## Tasks
* [x] Github backend
  * [x] `create`
    * [x] Write a test
    * [x] Get the test passing
  * [x] `update`
     * [x] Write a test
     * [x] Get the test passing
  * [x] `fetch`
    * [x] Write a test
    * [x] Get the test passing

## Detailed Analysis and Notes

```javascript=
import metastore from 'metastore-lib-js'

const config = {
    token: "dgkjdgjkd",
    org: "gift-data",
    metadataPath: "datapackage.json"
    author: "John Doe"
}

let store = new metastore.Github(config)
```

### Create metadata

Using the metastore instance above, we can store new metadata for an object by calling the metastore create method:

```javascript=
let objectId = "France-2020-budget" //This is also the repo name
# store a Frictionless Data Package https://specs.rictionless.io/data-package/
let metadata = {"name": "mypackage",
                    "version": "1.0.0",
                    "resources": [
                       # ...
                     ]}
let objectInfo = store.create(objectId, metadata)
```

The returned objectInfo will be an object with some information about the stored package revision.

### Update metadata

To update an existing package, provide the package_id and the metadata as shown below:
```javascript=
let package_id = "France-2020-budget" //This is also the repo name
let datapackage = {"name": "mypackage",
                    "version": "1.1.0",
                    "resources": [
                       # ...
                     ]}
let package_info = metastoreBackend.update(package_id, datapackage)
```

### Fetch metadata

You can retreive an existing data package using the fetch method on the GithubBackend class as shown below:
```javascript=
let package_id = "France-2020-budget" //This is also the repo name
let datapackage = metastoreBackend.fetch(package_id)
```

### Datatypes, Classes and Methods

Data types, classes and methods for packages & related models.

#### Object Info

The PackageInfo class holds metadata about a created package including version and revision number, created date, and basic description. 
```javascript=
/**
    author: Optional[str] = None
    created: datetime = None
    description: Optional[str] = None
    package: Optional[DataPackageType] = None
    package_id: str = None
    revision: str = None
**/
class metastore.PackageInfo{
    constructor(package_id,revision,created,author,description,package){
        this.package_id = package_id
        this.revision = revision || 1.0.0
        this.created = new Date()
        this.author = {name: "John Doe", email: "johndoe@mail.com"
        this.description = description || ""
        this.package = package || {}
    }
}
    
```    

### Storage Backend Interface

The storage bankend class shows CRUD methods for handling data packages with Github API. Internally we use [rest.js](https://octokit.github.io/rest.js/v18) library to handle interactions with Github API.

* Create a repository in an organisation ==> https://octokit.github.io/rest.js/v18#repos-create-in-org
* Upload/create and update file in a repository ==> https://octokit.github.io/rest.js/v18#repos-create-or-update-file-contents

```javascript=

class metastore.GithubBackend {
    constructor(config){
        this.personal_access_token = config.personal_access_token
        this.org_name = config.org_name
        this.author = config.author         
    }
    
    /**
     * Uploads a new data package
     * 
     * returns
     * PackageInfo
     **/
    upload(package_id, metadata, author, message){
        // creates metadata and uploads to Github with github client
    }
    
    /**
     * Deletes a data package from Github
     * 
     * Throws: Not found if the package does not exist
     * 
     * Returns None
    **/
    remove(package_id){
        //delete ops
    }
    
    /**
     * Update or partial update (patch) a data package
     * 
     * Returns PackageInfo
     **/
    update(package_id, metadata, author, message){
        //perform update
    }
    
    /**
     * Gets a data package by ID
     * 
     * Returns datapackage Object
     **/
    fetch(package_id){
        //perform update
    }
    
}
```
